nama    = input("Nama                   : ")
nim     = input("NIM                    : ")
paralel = input("Kelas Paralel          : ")
ttl     = input("Tempat/Tanggal lahir   : ")
alamat  = input("Alamat                 : ")
hobby   = input("Hobby                  : ")
noHP    = input("No HP                  : ")

print(f"Nama                     : {nama}")
print(f"NIM                      : {nim}")
print(f"Kelas Paralel            : {paralel}")
print(f"Tempat/Tanggal lahir     : {ttl}")
print(f"Alamat                   : {alamat}")
print(f"Hobby                    : {hobby}")
print(f"No HP                    : {noHP}")
