print("##############################")
print("#                            #")
print("#   Muhammad Azma Al Faqih   #")
print("#       2410817110008        #")
print("#                            #")
print("##############################")